# Generated by Django 4.2 on 2023-04-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_commited', models.CharField(max_length=64)),
                ('date', models.DateField(default='')),
                ('time_hour', models.IntegerField(default=0)),
                ('time_minute', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('district', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('block', models.CharField(max_length=64)),
            ],
        ),
    ]
